# SPDX-FileCopyrightText: Copyright (C) 2021-2026 Software Radio Systems Limited
# SPDX-License-Identifier: BSD-3-Clause-Open-MPI

# CUSTOMIZED 5G STANDALONE gNB CONFIGURATION (ZeroMQ + Docker)

# This configuration outlines a single FDD cell (Band 3, 20 MHz, 15 kHz SCS).
# 
# Custom Modifications:
# - Adapted to route virtual RF traffic across Docker bridge interfaces using ZeroMQ.
# - Configured to connect a containerized gNB (10.53.1.3) to a host-based srsUE.

cu_cp:
  amf:
    addrs: 10.53.1.2
    port: 38412
    bind_addrs: 10.53.1.1
    supported_tracking_areas:
      - tac: 7
        plmn_list:
          - plmn: "00101"
            tai_slice_support_list:
              - sst: 1

ru_sdr:
  device_driver: zmq
  device_args: tx_port=tcp://*:2000,rx_port=tcp://10.53.1.1:2001,base_srate=23.04e6
  srate: 23.04
  tx_gain: 80
  rx_gain: 40

cell_cfg:
  dl_arfcn: 368500
  band: 3
  channel_bandwidth_MHz: 20
  common_scs: 15
  plmn: "00101"
  tac: 7
  pdcch:
    dedicated:
      ss2_type: common
      dci_format_0_1_and_1_1: false
    common:
      ss0_index: 0
      coreset0_index: 12
  prach:
    prach_config_index: 1
  pdsch:
    mcs_table: qam64
  pusch:
    mcs_table: qam64

log:
  filename: stdout #/tmp/gnb.log
  all_level: info

pcap:
  mac_enable: false
  mac_filename: /tmp/gnb_mac.pcap
  ngap_enable: false
  ngap_filename: /tmp/gnb_ngap.pcap
