gnb_id: 3586

remote_control:
  enabled: true
  bind_addr: 0.0.0.0 #10.12.1.53
  port: 8001

cells:
  -
    pci: 1
  -
    pci: 2
  -
    pci: 3

cell_cfg:
  dl_arfcn: 625000
  band: 78
  channel_bandwidth_MHz: 100
  common_scs: 30
  plmn: "00101"
  tac: 1
  pci: 1
  prach:
    prach_config_index: 159
    prach_root_sequence_index: 1
    zero_correlation_zone: 0
  pdsch:
    mcs_table: qam256
  pusch:
    mcs_table: qam256
  nof_antennas_dl: 4
  nof_antennas_ul: 1

  tdd_ul_dl_cfg:
    dl_ul_tx_period: 10
    nof_dl_slots: 7
    nof_dl_symbols: 10
    nof_ul_slots: 2
    nof_ul_symbols: 0

expert_phy:
  pusch_dec_max_iterations: 2

log:
  all_level: warning
  config_level: debug

metrics:
  autostart_stdout_metrics: false
  enable_json: true
  layers:
    enable_ru: true
    enable_sched: true
    enable_rlc: true
    enable_mac: true
    enable_pdcp: true
    enable_du_low: true
    enable_app_usage: true

ru_dummy:

cu_cp:
  amf:
    no_core: true

test_mode:
  test_ue:
    rnti: 0x44
    ri: 4
    cqi: 15
    nof_ues: 16
    pusch_active: true
    pdsch_active: true
